name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.4
      - name: Build
        run: go build --buildmode=plugin -o ./plugin.so ./
      - name: Run coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic
      - name: actions-goveralls
        uses: shogo82148/actions-goveralls@v1.5.1
        with:
          path-to-profile: coverage.txt
