name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.4
      - name: Run coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic
      - name: actions-goveralls
        uses: shogo82148/actions-goveralls@v1.5.1
        with:
          path-to-profile: coverage.txt
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Buld and deploy artifact
      uses: wangyoucao577/go-release-action@v1.22
      with:
        github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        goos: linux
        goarch: amd64
        goversion: "https://dl.google.com/go/go1.16.4.linux-amd64.tar.gz"
        project_path: "./cmd/test-binary"
        build_flags: --buildmode=plugin
        extra_files: LICENSE README.md
